LOCAL = "local"
INTEGRATION = "integration"
SEARCH_CONT = "search_cont"



WORK_TYPE_LOCAL = "LOCAL"
WORK_TYPE_INTEGRATION = "INTEGRATION"
WORK_TYPE_SEARCH = "SEARCH"

WORK_TYPE_LOCAL_DELETE = "LOCAL_DEL"
WORK_TYPE_INTEGRATION_DELETE = "INTEGRATION_DEL"
WORK_TYPE_SEARCH_DELETE = "SEARCH_DEL"
WORK_TYPE_SEED_DELETE = "SEED_DEL"