# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: alpha.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x61lpha.proto\x12\x0c\x61lpha_encode\":\n\x07request\x12\x10\n\x08\x66unction\x18\x01 \x01(\t\x12\x0e\n\x06\x61\x63tion\x18\x02 \x01(\t\x12\r\n\x05query\x18\x03 \x01(\t\"\x1c\n\x08response\x12\x10\n\x08response\x18\x01 \x01(\t2l\n\x19\x41lphaStandardGRPCFunction\x12O\n\x1crpcAlphaStandardGRPCFunction\x12\x15.alpha_encode.request\x1a\x16.alpha_encode.response\"\x00\x62\x06proto3')



_REQUEST = DESCRIPTOR.message_types_by_name['request']
_RESPONSE = DESCRIPTOR.message_types_by_name['response']
request = _reflection.GeneratedProtocolMessageType('request', (_message.Message,), {
  'DESCRIPTOR' : _REQUEST,
  '__module__' : 'alpha_pb2'
  # @@protoc_insertion_point(class_scope:alpha_encode.request)
  })
_sym_db.RegisterMessage(request)

response = _reflection.GeneratedProtocolMessageType('response', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'alpha_pb2'
  # @@protoc_insertion_point(class_scope:alpha_encode.response)
  })
_sym_db.RegisterMessage(response)

_ALPHASTANDARDGRPCFUNCTION = DESCRIPTOR.services_by_name['AlphaStandardGRPCFunction']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REQUEST._serialized_start=29
  _REQUEST._serialized_end=87
  _RESPONSE._serialized_start=89
  _RESPONSE._serialized_end=117
  _ALPHASTANDARDGRPCFUNCTION._serialized_start=119
  _ALPHASTANDARDGRPCFUNCTION._serialized_end=227
# @@protoc_insertion_point(module_scope)